### ISSUE TITLE
Student Profile

### ISSUE THREAD

**Issue by rsbabcock** [nss-day-cohort-25-website/nss-day-cohort-25-website#2]
# Story

As a user, I should be able to view an individual student's info

## Acceptance Criteria

Given a user wants to view a students info
When the user scrolls down the page
All students profiles should be visible 
with profile image name, GitHub link, linked link and an info button.
And these links must connect to the actual hyperlink

Given a user wants to view a students info
When the user hovers over the info button
Then the student profile view should transform into student background/bio and extra links and student image should not be viewable
And when the user hovers off student profile the image and GitHub links should appear back

**Comment by RileyMathews** [comment]
- [ ] Display a students card on the dom

- [ ] get the card to flip on hover

- [ ] get the card to change based on the party button
